CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_C96_FIRE", "weapons/c96carbine/c96carbine_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_BOLTRELEASE", "weapons/c96carbine/handling/c96carbine_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_EMPTY", "weapons/c96carbine/handling/c96carbine_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_FETCHMAG", "weapons/c96carbine/handling/c96carbine_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_MAGFIDDLE", "weapons/c96carbine/handling/c96carbine_magfiddle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_MAGIN", "weapons/c96carbine/handling/c96carbine_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_MAGOUT", "weapons/c96carbine/handling/c96carbine_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_MAGRELEASE", "weapons/c96carbine/handling/c96carbine_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_RATTLE", "weapons/c96carbine/handling/c96carbine_rattle.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_STRIPPER_IN", "weapons/c96carbine/handling/c96_strippr_clip_in.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_STRIPPER_REMOVE", "weapons/c96carbine/handling/c96_strippr_clip_remove.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_STRIPPER_ROUNDSIN1", "weapons/c96carbine/handling/c96_strippr_clip_rounds_in_01.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_C96_STRIPPER_ROUNDSIN2", "weapons/c96carbine/handling/c96_strippr_clip_rounds_in_02.wav")
