CustomizableWeaponry:addFireSound("CW_KK_INS2_CSTM_SCAR_FIRE", "weapons/cw_kk_ins2_cstm_scar/m14_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_CSTM_SCAR_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_cstm_scar/m14_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_BOLTBACK", "weapons/cw_kk_ins2_cstm_scar/handling/m14_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_BOLTRELEASE", "weapons/cw_kk_ins2_cstm_scar/handling/m14_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_EMPTY", "weapons/cw_kk_ins2_cstm_scar/handling/m14_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_FIRESELECT", "weapons/cw_kk_ins2_cstm_scar/handling/m14_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_MAGIN", "weapons/cw_kk_ins2_cstm_scar/handling/m14_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_MAGOUT", "weapons/cw_kk_ins2_cstm_scar/handling/m14_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_MAGOUTRATTLE", "weapons/cw_kk_ins2_cstm_scar/handling/m14_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_MAGRELEASE", "weapons/cw_kk_ins2_cstm_scar/handling/m14_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_CSTM_SCAR_RATTLE", "weapons/cw_kk_ins2_cstm_scar/handling/m14_rattle.wav")
