CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_OWEN_FIRE", "weapons/owen/owen_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_BOLTBACK", "weapons/owen/handling/owen_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_BOLTLOCK", "weapons/owen/handling/owen_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_BOLTUNLOCK", "weapons/owen/handling/owen_boltunlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_EMPTY", "weapons/owen/handling/owen_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_FETCHMAG", "weapons/owen/handling/owen_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_FIRESELECT", "weapons/owen/handling/owen_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_MAGHIT", "weapons/owen/handling/owen_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_MAGIN", "weapons/owen/handling/owen_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_MAGOUT", "weapons/owen/handling/owen_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_MAGRELEASE", "weapons/owen/handling/owen_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_OWEN_RATTLE", "weapons/owen/handling/owen_rattle.wav")
