CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_P38_FIRE", "weapons/p38/p38_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P38_BOLTBACK", "weapons/p38/handling/p38_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P38_BOLTRELEASE", "weapons/p38/handling/p38_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P38_EMPTY", "weapons/p38/handling/p38_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P38_MAGHIT", "weapons/p38/handling/p38_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P38_MAGIN", "weapons/p38/handling/p38_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P38_MAGOUT", "weapons/p38/handling/p38_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P38_MAGRELEASE", "weapons/p38/handling/p38_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P38_SAFETY", "weapons/p38/handling/p38_safety.wav")