CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_PPK_FIRE", "weapons/ppk/ppk_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_PPK_BOLTBACK", "weapons/ppk/handling/ppk_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_PPK_BOLTRELEASE", "weapons/ppk/handling/ppk_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_PPK_EMPTY", "weapons/ppk/handling/ppk_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_PPK_MAGHIT", "weapons/ppk/handling/ppk_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_PPK_MAGIN", "weapons/ppk/handling/ppk_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_PPK_MAGOUT", "weapons/ppk/handling/ppk_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_PPK_MAGRELEASE", "weapons/ppk/handling/ppk_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_PPK_SAFETY", "weapons/ppk/handling/ppk_safety.wav")