CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_BHP_FIRE", "weapons/browninghp/browning_hp_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BHP_BOLTBACK", "weapons/browninghp/handling/browning_hp_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BHP_BOLTRELEASE", "weapons/browninghp/handling/browning_hp_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BHP_EMPTY", "weapons/browninghp/handling/browning_hp_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BHP_MAGHIT", "weapons/browninghp/handling/browning_hp_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BHP_MAGIN", "weapons/browninghp/handling/browning_hp_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BHP_MAGOUT", "weapons/browninghp/handling/browning_hp_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BHP_MAGRELEASE", "weapons/browninghp/handling/browning_hp_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BHP_SAFETY", "weapons/browninghp/handling/browning_hp_safety.wav")