CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_FG42_FIRE", "weapons/fg42/fg42_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_BOLTBACK", "weapons/fg42/handling/fg42_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_EMPTY", "weapons/fg42/handling/fg42_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_FIRESELECT", "weapons/fg42/handling/fg42_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_MAGFETCH", "weapons/fg42/handling/fg42_mag_fetch.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_MAGHIT", "weapons/fg42/handling/fg42_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_MAGIN", "weapons/fg42/handling/fg42_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_MAGOUT", "weapons/fg42/handling/fg42_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_MAGRELEASE", "weapons/fg42/handling/fg42_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_FG42_RATTLE", "weapons/fg42/handling/fg42_rattle.wav")
