CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_P08_FIRE", "weapons/p08/p08_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P08_BOLTBACK", "weapons/p08/handling/p08_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P08_BOLTRELEASE", "weapons/p08/handling/p08_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P08_EMPTY", "weapons/p08/handling/p08_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P08_MAGHIT", "weapons/p08/handling/p08_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P08_MAGIN", "weapons/p08/handling/p08_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P08_MAGOUT", "weapons/p08/handling/p08_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P08_MAGRELEASE", "weapons/p08/handling/p08_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_P08_SAFETY", "weapons/p08/handling/p08_safety.wav")