CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_MP40_FIRE", "weapons/cw_kk_doi_mp40/mp40_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_BOLTBACK", "weapons/cw_kk_doi_mp40/handling/mp40_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_BOLTLOCK", "weapons/cw_kk_doi_mp40/handling/mp40_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_BOLTUNLOCK", "weapons/cw_kk_doi_mp40/handling/mp40_boltunlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_EMPTY", "weapons/cw_kk_doi_mp40/handling/mp40_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_FIRESELECT", "weapons/cw_kk_doi_mp40/handling/mp40_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_MAGHIT", "weapons/cw_kk_doi_mp40/handling/mp40_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_MAGIN", "weapons/cw_kk_doi_mp40/handling/mp40_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_MAGOUT", "weapons/cw_kk_doi_mp40/handling/mp40_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MP40_MAGRELEASE", "weapons/cw_kk_doi_mp40/handling/mp40_magrelease.wav")
