CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_STEN_FIRE", "weapons/sten/sten_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_STEN_FIRE_SUPPRESSED", "weapons/sten/sten_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_BOLTBACK", "weapons/sten/handling/sten_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_BOLTLOCK", "weapons/sten/handling/sten_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_BOLTUNLOCK", "weapons/sten/handling/sten_boltunlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_EMPTY", "weapons/sten/handling/sten_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_FETCHMAG", "weapons/sten/handling/sten_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_FIRESELECT", "weapons/sten/handling/sten_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_MAGHIT", "weapons/sten/handling/sten_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_MAGIN", "weapons/sten/handling/sten_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_MAGOUT", "weapons/sten/handling/sten_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_MAGRELEASE", "weapons/sten/handling/sten_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_RATTLE", "weapons/sten/handling/sten_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_STOCKOPEN1", "weapons/sten/handling/sten_stockopen_01.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_STEN_STOCKOPEN2", "weapons/sten/handling/sten_stockopen_02.wav")
