CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_VICKERS_FIRE", "weapons/vickers/vickers_fp.wav", 1, 100, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_BELTALIGN", "weapons/vickers/handling/vickers_beltalign.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_BELTDROP", "weapons/vickers/handling/vickers_beltdrop.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_BELTJINGLE", "weapons/vickers/handling/vickers_beltjingle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_BELTPULL", "weapons/vickers/handling/vickers_beltpull.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_BOLTBACK", "weapons/vickers/handling/vickers_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_BOLTRELEASE", "weapons/vickers/handling/vickers_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_DEPLOYGROUNDHIT", "weapons/vickers/handling/vickers_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_EMPTY", "weapons/vickers/handling/vickers_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_FETCHMAG", "weapons/vickers/handling/vickers_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_VICKERS_SHOULDER", "weapons/vickers/handling/vickers_shoulder_weapon.wav")
