CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_M1A1_FIRE", "weapons/m1carbine_para/m1carbine_para_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_BOLTBACK", "weapons/m1carbine_para/handling/m1carbine_para_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_BOLTRELEASE", "weapons/m1carbine_para/handling/m1carbine_para_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_EMPTY", "weapons/m1carbine_para/handling/m1carbine_para_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_MAGIN", "weapons/m1carbine_para/handling/m1carbine_para_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_MAGOUT", "weapons/m1carbine_para/handling/m1carbine_para_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_MAGRELEASE", "weapons/m1carbine_para/handling/m1carbine_para_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_RATTLE", "weapons/m1carbine_para/handling/m1carbine_para_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_STOCK1", "weapons/m1carbine_para/handling/m1carbine_para_stockopen_01.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_M1A1_STOCK2", "weapons/m1carbine_para/handling/m1carbine_para_stockopen_02.wav")
