CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_LEWIS_FIRE", "weapons/lewis/lewis_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_BOLTBACK", "weapons/lewis/handling/lewis_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_DEPLOYGROUNDHIT", "weapons/lewis/handling/lewis_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_EMPTY", "weapons/lewis/handling/lewis_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_FETCHMAG", "weapons/lewis/handling/lewis_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_MAGFIDDLE", "weapons/lewis/handling/lewis_magfiddle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_MAGHIT", "weapons/lewis/handling/lewis_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_MAGIN", "weapons/lewis/handling/lewis_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_MAGOUT", "weapons/lewis/handling/lewis_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_MAGOUTFULL", "weapons/lewis/handling/lewis_magoutfull.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_MAGRELEASE", "weapons/lewis/handling/lewis_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_RATTLE", "weapons/lewis/handling/lewis_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_LEWIS_SHOULDERWEAPON", "weapons/lewis/handling/lewis_shoulder_weapon.wav")
