CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_BREN_FIRE", "weapons/bren/bren_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_BOLTBACK", "weapons/bren/handling/bren_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_BOLTRELEASE", "weapons/bren/handling/bren_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_DEPLOYGROUNDHIT", "weapons/bren/handling/bren_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_EMPTY", "weapons/bren/handling/bren_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_FETCHMAG", "weapons/bren/handling/bren_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_MAGHIT", "weapons/bren/handling/bren_mag_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_MAGIN", "weapons/bren/handling/bren_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_MAGOUT", "weapons/bren/handling/bren_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_MAGRELEASE", "weapons/bren/handling/bren_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_RATTLE", "weapons/bren/handling/bren_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BREN_SHOULDERWEAPON", "weapons/bren/handling/bren_shoulder_weapon.wav")
