CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_MG34_FIRE", "weapons/mg34/mg34_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_BELTALIGN", "weapons/mg34/handling/mg34_beltalign.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_BIPODDEPLOY", "weapons/mg34/handling/mg34_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_BIPODRETRACT", "weapons/mg34/handling/mg34_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_BOLTBACK", "weapons/mg34/handling/mg34_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_BOLTRELEASE", "weapons/mg34/handling/mg34_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_COVERCLOSE", "weapons/mg34/handling/mg34_coverclose.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_COVEROPEN", "weapons/mg34/handling/mg34_coveropen.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_DEPLOYGROUNDHIT", "weapons/mg34/handling/mg34_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_EMPTY", "weapons/mg34/handling/mg34_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_ENDDEPLOYEDRELOAD", "weapons/mg34/handling/mg34_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_FETCHMAG", "weapons/mg34/handling/mg34_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_FIRESELECT", "weapons/mg34/handling/mg34_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_MAGFETCH", "weapons/mg34/handling/mg34_mag_fetch.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_MAGHIT", "weapons/mg34/handling/mg34_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_MAGIN", "weapons/mg34/handling/mg34_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_MAGOUT", "weapons/mg34/handling/mg34_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_MAGOUTFULL", "weapons/mg34/handling/mg34_magout_full.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_MAGOUTRATTLE", "weapons/mg34/handling/mg34_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_MAGRELEASE", "weapons/mg34/handling/mg34_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_RATTLE", "weapons/mg34/handling/mg34_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_MG34_SHOULDERWEAPON", "weapons/mg34/handling/mg34_shoulder_weapon.wav")
