CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_BAR_FIRE", "weapons/bar/bar_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_BIPODDEPLOY", "weapons/bar/handling/bar_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_BIPODRETRACT", "weapons/bar/handling/bar_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_BOLTBACK", "weapons/bar/handling/bar_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_BOLTRELEASE", "weapons/bar/handling/bar_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_DEPLOYGROUNDHIT", "weapons/bar/handling/bar_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_EMPTY", "weapons/bar/handling/bar_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_ENDDEPLOYEDRELOAD", "weapons/bar/handling/bar_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_FETCHMAG", "weapons/bar/handling/bar_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_FIRESELECT", "weapons/bar/handling/bar_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_MAGHIT", "weapons/bar/handling/bar_mag_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_MAGIN", "weapons/bar/handling/bar_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_MAGOUT", "weapons/bar/handling/bar_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_MAGOUTRATTLE", "weapons/bar/handling/bar_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_MAGRELEASE", "weapons/bar/handling/bar_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_BAR_RATTLE", "weapons/bar/handling/bar_rattle.wav")
